// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;

namespace SchooxSharp.Api.Models
{

    public class User
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("firstname")]
        public string Firstname { get; set; }

        [JsonProperty("lastname")]
        public string Lastname { get; set; }

        [JsonProperty("email")]
        public object Email { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("total_course_hours")]
        public string TotalCourseHours { get; set; }

        [JsonProperty("total_courses")]
        public int TotalCourses { get; set; }

        [JsonProperty("total_exams")]
        public int TotalExams { get; set; }
    }

    public class Certificate
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("ver_code")]
        public string VerCode { get; set; }

        [JsonProperty("total_time")]
        public int TotalTime { get; set; }

        [JsonProperty("time_certified")]
        public string TimeCertified { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class Course
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("students")]
        public int Students { get; set; }

        [JsonProperty("completion_rate")]
        public int CompletionRate { get; set; }

        [JsonProperty("publish_date")]
        public string PublishDate { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("total_time")]
        public string TotalTime { get; set; }

        [JsonProperty("enroll_date")]
        public string EnrollDate { get; set; }

        [JsonProperty("certificates")]
        public List<Certificate> Certificates { get; set; }

        [JsonProperty("due_date")]
        public string DueDate { get; set; }

        [JsonProperty("is_due")]
        public bool IsDue { get; set; }
    }


    public class Curriculum
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("total_time")]
        public string TotalTime { get; set; }

        [JsonProperty("enroll_date")]
        public string EnrollDate { get; set; }
    }



    public class LastAttempt
    {

        [JsonProperty("date_start")]
        public string DateStart { get; set; }

        [JsonProperty("date_end")]
        public string DateEnd { get; set; }
    }

    public class Points
    {

        [JsonProperty("got")]
        public int Got { get; set; }

        [JsonProperty("all")]
        public int All { get; set; }
    }

    public class Exam
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("instructions")]
        public string Instructions { get; set; }

        [JsonProperty("attempts")]
        public int Attempts { get; set; }

        [JsonProperty("last_attempt")]
        public LastAttempt LastAttempt { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("points")]
        public Points Points { get; set; }

        [JsonProperty("passed")]
        public bool Passed { get; set; }
    }


    public class Certificate
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("ver_code")]
        public string VerCode { get; set; }

        [JsonProperty("total_time")]
        public int TotalTime { get; set; }

        [JsonProperty("time_certified")]
        public string TimeCertified { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class UserInCourse
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("firstname")]
        public string Firstname { get; set; }

        [JsonProperty("lastname")]
        public string Lastname { get; set; }

        [JsonProperty("email")]
        public object Email { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("enrolment_date")]
        public string EnrolmentDate { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("due_date")]
        public string DueDate { get; set; }

        [JsonProperty("certificates")]
        public Certificate[] Certificates { get; set; }
    }


    public class Lecture
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }
    }

    public class Points
    {

        [JsonProperty("got")]
        public int Got { get; set; }

        [JsonProperty("all")]
        public int All { get; set; }
    }

    public class Exam
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("last_attempt")]
        public string LastAttempt { get; set; }

        [JsonProperty("passed")]
        public bool Passed { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("points")]
        public Points Points { get; set; }
    }

    public class Certificate
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("ver_code")]
        public string VerCode { get; set; }

        [JsonProperty("total_time")]
        public int TotalTime { get; set; }

        [JsonProperty("time_certified")]
        public string TimeCertified { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class UserProgressInCourse
    {

        [JsonProperty("lectures")]
        public Lecture[] Lectures { get; set; }

        [JsonProperty("exams")]
        public Exam[] Exams { get; set; }

        [JsonProperty("certificates")]
        public Certificate[] Certificates { get; set; }
    }


    public class Curriculum
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("students")]
        public int Students { get; set; }

        [JsonProperty("completion_rate")]
        public int CompletionRate { get; set; }

        [JsonProperty("publish_date")]
        public string PublishDate { get; set; }
    }

    public class User
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("firstname")]
        public string Firstname { get; set; }

        [JsonProperty("lastname")]
        public string Lastname { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("enrolment_date")]
        public string EnrolmentDate { get; set; }

        [JsonProperty("due_date")]
        public string DueDate { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }
    }
 

    public class CurriculumProgress
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }
    }


    public class Exam
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("students")]
        public int Students { get; set; }

        [JsonProperty("success_rate")]
        public int SuccessRate { get; set; }

        [JsonProperty("average_score")]
        public int AverageScore { get; set; }
    }


    public class Points
    {

        [JsonProperty("got")]
        public int Got { get; set; }

        [JsonProperty("all")]
        public int All { get; set; }
    }

    public class UsersInExam
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("firstname")]
        public string Firstname { get; set; }

        [JsonProperty("lastname")]
        public string Lastname { get; set; }

        [JsonProperty("email")]
        public object Email { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("attempts")]
        public int Attempts { get; set; }

        [JsonProperty("last_attempt")]
        public string LastAttempt { get; set; }

        [JsonProperty("passed")]
        public bool Passed { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("points")]
        public Points Points { get; set; }
    }

}
