// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SchooxSharp.Api.Models
{

    public class NewJob
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("report_id")]
        public int? ReportId { get; set; }

        public override string ToString()
        {
            return string.Format("Name: {0}, ReportId: {1}", Name, ReportId);
        }
    }

}
