using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SchooxSharp.Api.Models
{

    public class UpdateUserJob
    {
        public UpdateUserJob()
        {
            
        }

        public UpdateUserJob(int? unit, int? aboveUnit, params int[] jobs)
        {
            Unit = unit;
            AboveUnit = aboveUnit;
            Jobs = jobs.ToList();
        }

        [JsonProperty("unit")]
        public int? Unit { get; set; }

        [JsonProperty("jobs")]
        public List<int> Jobs { get; set; }

        [JsonProperty("above_unit")]
        public int? AboveUnit { get; set; }
    }

}
